FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Defining the workdir of my container
WORKDIR /app

# Copying the requirements
COPY requirements.txt .

# Installing dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the whole project into the container
COPY . .

# Starting the aplication
CMD ["python", "main.py"]