# Configurações essenciais para o Debezium
listen_addresses = '*'

# Nível do log: 'logical' permite que o Debezium entenda as mudanças
wal_level = logical             

# Número de slots de replicação (pelo menos 1 para o Debezium)
max_replication_slots = 4       

# Número de processos de envio de log
max_wal_senders = 4